### ISSUE TITLE
Instructor Feedback - Week 8

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [MadJavaEntFall2017/DecisionMaker#9]
Looks like you have a good start on your Decision Maker service.

- [x] Be sure to add the problem statement and solution to the readme.md. In the solution explanation, I'm looking for details on inputs/outputs. What types of responses will be provided. I'll use this to help scope the project to ensure it meets expectations for a 4-person team. 
- [x] Review the rest api naming standard best practices. For example, generally the resource name will be plural: decisions versus decision.
- [x] Project plan?

**Comment by ssoperMadisonCollege** [comment]
Thanks for feedback, Paula.  We'll address this soon.
